// Generates src/lib/factor/data.ts — a static, build-time snapshot of the
// factor-model universe (composites + block scores per fiscal year).
// Pages never depend on the DB; this file is the page-facing source of truth
// (see docs/ARCHITECTURE.md rule: pages never depend on the DB).
//
// Run: npx tsx scripts/factor-model/snapshot.ts
// Source: local Supabase mirror seeded by npm run factor:import.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import pg from "pg";

const __dir = dirname(fileURLToPath(import.meta.url));

try {
  const envPath = join(__dir, "../../.env.local");
  for (const line of readFileSync(envPath, "utf8").split(/\r?\n/)) {
    const m = line.match(/^\s*([\w.]+)\s*=\s*(.*)\s*$/);
    if (m && !process.env[m[1]]) process.env[m[1]] = m[2];
  }
} catch {
  /* no .env.local -> rely on real env */
}

const DATABASE_URL = process.env.DATABASE_URL;
if (!DATABASE_URL) {
  console.error("DATABASE_URL missing (set it in .env.local)");
  process.exit(1);
}

const pool = new pg.Pool({ connectionString: DATABASE_URL, max: 4 });

async function main() {
  const { rows } = await pool.query(`
    SELECT
      c.fiscal_year,
      c.ric,
      fc.name,
      fc.company_slug AS slug,
      fc.sector,
      c.rank,
      c.composite,
      g.score  AS growth,
      q.score  AS quality,
      v.score  AS valuation,
      m.score  AS momentum
    FROM factor_composites c
    JOIN factor_companies fc USING (ric)
    LEFT JOIN factor_scores g ON g.ric = c.ric AND g.fiscal_year = c.fiscal_year AND g.block = 'growth'
    LEFT JOIN factor_scores q ON q.ric = c.ric AND q.fiscal_year = c.fiscal_year AND q.block = 'quality'
    LEFT JOIN factor_scores v ON v.ric = c.ric AND v.fiscal_year = c.fiscal_year AND v.block = 'valuation'
    LEFT JOIN factor_scores m ON m.ric = c.ric AND m.fiscal_year = c.fiscal_year AND m.block = 'momentum'
    ORDER BY c.fiscal_year, c.rank
  `);

  const years = [...new Set(rows.map((r) => r.fiscal_year))].sort((a, b) => a - b);
  const byYear = new Map<number, unknown[][]>();
  for (const r of rows) {
    if (!byYear.has(r.fiscal_year)) byYear.set(r.fiscal_year, []);
    byYear.get(r.fiscal_year)!.push([
      r.ric,
      r.name,
      r.slug,
      r.sector,
      r.rank,
      Number(r.composite),
      r.growth === null ? null : Number(r.growth),
      r.quality === null ? null : Number(r.quality),
      r.valuation === null ? null : Number(r.valuation),
      r.momentum === null ? null : Number(r.momentum),
    ]);
  }

  const fmt = (x: unknown) => JSON.stringify(x);
  const lines: string[] = [];
  lines.push("// GENERATED by scripts/factor-model/snapshot.ts - DO NOT EDIT.");
  lines.push("// Build-time static snapshot of the factor model (composites per");
  lines.push("// fiscal year). Regenerate after npm run factor:import.");
  lines.push("");
  lines.push("/** [ric, name, companySlug|null, sector|null, rank, composite, growth, quality, valuation, momentum] */");
  lines.push("export type FactorRowTuple = [string, string, string | null, string | null, number, number, number | null, number | null, number | null, number | null];");
  lines.push("");
  lines.push("export const FACTOR_YEARS: number[] = " + fmt(years) + ";");
  lines.push("");
  lines.push("export const FACTOR_BY_YEAR: Record<number, FactorRowTuple[]> = {");
  for (const [year, rowsArr] of [...byYear.entries()].sort(([a], [b]) => a - b)) {
    lines.push(`  ${year}: ${fmt(rowsArr)},`);
  }
  lines.push("};");
  lines.push("");

  const outPath = join(__dir, "../../src/lib/factor/data.ts");
  writeFileSync(outPath, lines.join("\n"), "utf8");
  console.log(`snapshot written: ${outPath}`);
  console.log(`years: ${years.join(", ")}; total rows: ${rows.length}`);
  await pool.end();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
