// GENERATED by scripts/factor-model/optimize.ts - DO NOT EDIT.
// GQVM model configuration (source: GQVM Factor Dashboard.xlsx, Parameters
// tab — the dashboard's recommended configuration). Backtest signal years
// FY13..FY25; forward returns to FY26. Regenerate after re-importing the
// workbook: npm run factor:optimize

import type { BacktestParams } from "./engine";

/** Metric catalog for the backtest controls (display names). */
export const FACTOR_METRICS: { key: string; block: string; displayName: string; higherIsBetter: boolean }[] = [
  { key: "rev_3yr_cagr", block: "growth", displayName: "Revenue 3Y CAGR", higherIsBetter: true },
  { key: "rev_5yr_cagr", block: "growth", displayName: "Revenue 5Y CAGR", higherIsBetter: true },
  { key: "ebitda_3yr_cagr", block: "growth", displayName: "EBITDA 3Y CAGR", higherIsBetter: true },
  { key: "ebitda_5yr_cagr", block: "growth", displayName: "EBITDA 5Y CAGR", higherIsBetter: true },
  { key: "pat_3yr_cagr", block: "growth", displayName: "PAT 3Y CAGR", higherIsBetter: true },
  { key: "pat_5yr_cagr", block: "growth", displayName: "PAT 5Y CAGR", higherIsBetter: true },
  { key: "eps_3yr_cagr", block: "growth", displayName: "EPS 3Y CAGR", higherIsBetter: true },
  { key: "cfo_3yr_cagr", block: "growth", displayName: "CFO 3Y CAGR", higherIsBetter: true },
  { key: "roce", block: "quality", displayName: "ROCE", higherIsBetter: true },
  { key: "roe", block: "quality", displayName: "ROE", higherIsBetter: true },
  { key: "div_payout_ratio", block: "quality", displayName: "Dividend Payout Ratio", higherIsBetter: true },
  { key: "ni_to_cfo", block: "quality", displayName: "NI to CFO", higherIsBetter: true },
  { key: "current_ratio", block: "quality", displayName: "Current Ratio", higherIsBetter: true },
  { key: "interest_coverage", block: "quality", displayName: "Interest Coverage", higherIsBetter: true },
  { key: "net_debt_equity", block: "quality", displayName: "Net Debt / Equity", higherIsBetter: false },
  { key: "net_trade_cycle", block: "quality", displayName: "Net Trade Cycle", higherIsBetter: false },
  { key: "pe", block: "valuation", displayName: "P/E", higherIsBetter: false },
  { key: "pbv", block: "valuation", displayName: "P/BV", higherIsBetter: false },
  { key: "pcf", block: "valuation", displayName: "P/CF", higherIsBetter: false },
  { key: "pcfo", block: "valuation", displayName: "P/CFO", higherIsBetter: false },
  { key: "pfcf", block: "valuation", displayName: "P/FCF", higherIsBetter: false },
  { key: "ev_ebit", block: "valuation", displayName: "EV/EBIT", higherIsBetter: false },
  { key: "ev_ebitda", block: "valuation", displayName: "EV/EBITDA", higherIsBetter: false },
  { key: "momentum_1y", block: "momentum", displayName: "Momentum (1Y)", higherIsBetter: true },
];

export const DEFAULT_BACKTEST_PARAMS: BacktestParams = {
  blockWeights: {
    growth: 0.2,
    quality: 0.1,
    valuation: 0.6,
    momentum: 0.1,
  },
  metricWeights: {
    "rev_3yr_cagr": 1,
    "rev_5yr_cagr": 1,
    "ebitda_3yr_cagr": 1,
    "ebitda_5yr_cagr": 1,
    "pat_3yr_cagr": 1,
    "pat_5yr_cagr": 1,
    "eps_3yr_cagr": 1,
    "cfo_3yr_cagr": 1,
    "roce": 1,
    "roe": 1,
    "div_payout_ratio": 1,
    "ni_to_cfo": 1,
    "current_ratio": 1,
    "interest_coverage": 1,
    "net_debt_equity": 1,
    "net_trade_cycle": 1,
    "pe": 1,
    "pbv": 1,
    "pcf": 1,
    "pcfo": 1,
    "pfcf": 1,
    "ev_ebit": 1,
    "ev_ebitda": 1,
    "momentum_1y": 1,
  },
  minN: 2,
  minFactors: 3,
  topN: 20,
};

/** GQVM recommended-configuration results (informational; in-sample FY13..FY25). */
export const OPTIMIZER_SUMMARY = {
  years: "FY13..FY25",
  meanPortfolioReturn: 0.1996657404139828,
  meanBenchmarkReturn: 0.12585062789847715,
  meanExcessReturn: 0.07381511251550564,
  cagr: 0.18140379399916218,
  vol: 0.21658598521057337,
  sharpe: 0.6217657171264128,
  maxDrawdown: -0.11061811554973922,
  hitRate: 0.6923076923076923,
  informationRatio: 0.32131190211583643,
  navFinal: 873.3306375150573,
  riskFreeRate: 0.065,
} as const;