// GENERATED by scripts/factor-model/optimize.ts - DO NOT EDIT.
// Default backtest parameters chosen to maximize the mean Top-N
// portfolio return over FY13..FY25 (grid search, growth/quality/valuation/momentum blocks, per-metric inclusion, MinN, TopN).
// Regenerate after re-importing the workbook: npm run factor:optimize

import type { BacktestParams } from "./engine";

/** Metric catalog for the backtest controls (display names). */
export const FACTOR_METRICS: { key: string; block: string; displayName: string; higherIsBetter: boolean }[] = [
  { key: "rev_3yr_cagr", block: "growth", displayName: "Revenue 3Y CAGR", higherIsBetter: true },
  { key: "rev_5yr_cagr", block: "growth", displayName: "Revenue 5Y CAGR", higherIsBetter: true },
  { key: "ebitda_3yr_cagr", block: "growth", displayName: "EBITDA 3Y CAGR", higherIsBetter: true },
  { key: "ebitda_5yr_cagr", block: "growth", displayName: "EBITDA 5Y CAGR", higherIsBetter: true },
  { key: "pat_3yr_cagr", block: "growth", displayName: "PAT 3Y CAGR", higherIsBetter: true },
  { key: "pat_5yr_cagr", block: "growth", displayName: "PAT 5Y CAGR", higherIsBetter: true },
  { key: "eps_3yr_cagr", block: "growth", displayName: "EPS 3Y CAGR", higherIsBetter: true },
  { key: "cfo_3yr_cagr", block: "growth", displayName: "CFO 3Y CAGR", higherIsBetter: true },
  { key: "roce", block: "quality", displayName: "ROCE", higherIsBetter: true },
  { key: "roe", block: "quality", displayName: "ROE", higherIsBetter: true },
  { key: "div_payout_ratio", block: "quality", displayName: "Dividend Payout Ratio", higherIsBetter: true },
  { key: "ni_to_cfo", block: "quality", displayName: "NI to CFO", higherIsBetter: false },
  { key: "current_ratio", block: "quality", displayName: "Current Ratio", higherIsBetter: true },
  { key: "interest_coverage", block: "quality", displayName: "Interest Coverage", higherIsBetter: true },
  { key: "net_debt_equity", block: "quality", displayName: "Net Debt / Equity", higherIsBetter: false },
  { key: "net_trade_cycle", block: "quality", displayName: "Net Trade Cycle", higherIsBetter: false },
  { key: "pe", block: "valuation", displayName: "P/E", higherIsBetter: false },
  { key: "pbv", block: "valuation", displayName: "P/BV", higherIsBetter: false },
  { key: "pcf", block: "valuation", displayName: "P/CF", higherIsBetter: false },
  { key: "pcfo", block: "valuation", displayName: "P/CFO", higherIsBetter: false },
  { key: "pfcf", block: "valuation", displayName: "P/FCF", higherIsBetter: false },
  { key: "ev_ebit", block: "valuation", displayName: "EV/EBIT", higherIsBetter: false },
  { key: "ev_ebitda", block: "valuation", displayName: "EV/EBITDA", higherIsBetter: false },
  { key: "momentum_1y", block: "momentum", displayName: "Momentum (1Y)", higherIsBetter: true },
];

export const DEFAULT_BACKTEST_PARAMS: BacktestParams = {
  blockWeights: {
    growth: 0,
    quality: 0,
    valuation: 1,
    momentum: 0,
  },
  metricWeights: {
    "rev_3yr_cagr": 0,
    "rev_5yr_cagr": 0,
    "ebitda_3yr_cagr": 0,
    "ebitda_5yr_cagr": 0,
    "pat_3yr_cagr": 0,
    "pat_5yr_cagr": 0,
    "eps_3yr_cagr": 0,
    "cfo_3yr_cagr": 0,
    "roce": 0.125,
    "roe": 0.125,
    "div_payout_ratio": 0.125,
    "ni_to_cfo": 0.125,
    "current_ratio": 0.125,
    "interest_coverage": 0.125,
    "net_debt_equity": 0.125,
    "net_trade_cycle": 0.125,
    "pe": 1,
    "pbv": 0,
    "pcf": 0,
    "pcfo": 0,
    "pfcf": 0,
    "ev_ebit": 0,
    "ev_ebitda": 0,
    "momentum_1y": 0,
  },
  minN: 50,
  topN: 20,
};

/** Search result metadata (informational). */
export const OPTIMIZER_SUMMARY = {
  years: "FY13..FY25",
  meanPortfolioReturn: 0.25471914793235967,
  meanBenchmarkReturn: 0.12074973659556418,
  meanExcessReturn: 0.1339694113367955,
} as const;